import type { BusinessProfile, Location, Partner } from "./types";

/** Approximate coordinates for Mindanao hubs used in the demo. */
const CITY: Record<string, Location> = {
  davao: { name: "Davao City", lat: 7.19, lng: 125.46 },
  digos: { name: "Digos, Davao del Sur", lat: 6.75, lng: 125.35 },
  tagum: { name: "Tagum, Davao del Norte", lat: 7.45, lng: 125.81 },
  mati: { name: "Mati, Davao Oriental", lat: 6.95, lng: 126.22 },
  genSan: { name: "General Santos", lat: 6.11, lng: 125.17 },
  koronadal: { name: "Koronadal, South Cotabato", lat: 6.5, lng: 124.85 },
  cotabato: { name: "Cotabato City", lat: 7.22, lng: 124.25 },
  cdo: { name: "Cagayan de Oro", lat: 8.48, lng: 124.65 },
  butuan: { name: "Butuan, Agusan del Norte", lat: 8.95, lng: 125.54 },
  malaybalay: { name: "Malaybalay, Bukidnon", lat: 8.15, lng: 125.13 },
  kidapawan: { name: "Kidapawan, Cotabato", lat: 7.01, lng: 125.09 },
  zambo: { name: "Zamboanga City", lat: 6.92, lng: 122.08 },
  manila: { name: "Metro Manila", lat: 14.60, lng: 120.98 },
  baguio: { name: "Baguio City", lat: 16.41, lng: 120.59 },
  batangas: { name: "Batangas City", lat: 13.75, lng: 121.05 },
  palawan: { name: "Puerto Princesa", lat: 9.98, lng: 118.78 },
  cebu: { name: "Cebu City", lat: 10.29, lng: 123.90 },
  iloilo: { name: "Iloilo City", lat: 10.58, lng: 122.15 },
  bacolod: { name: "Bacolod City", lat: 10.67, lng: 122.95 },
  tacloban: { name: "Tacloban City", lat: 11.24, lng: 125.00 },
  legazpi: { name: "Legazpi City", lat: 13.14, lng: 123.73 },
};

/** The full Tuloy network of buyers and suppliers (demo dataset). */
export const NETWORK: Partner[] = [
  // ---- Buyers (for copra sellers) ----
  {
    id: "b-oleo-genSan",
    name: "SouthPoint Oleochemicals",
    role: "buyer",
    location: CITY.genSan,
    products: ["copra", "coconut_oil"],
    capacityTons: 220,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 41500,
    verified: true,
    rating: 4.7,
  },
  {
    id: "b-mill-digos",
    name: "Digos Copra Milling Co-op",
    role: "buyer",
    location: CITY.digos,
    products: ["copra"],
    capacityTons: 90,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 40200,
    verified: true,
    rating: 4.5,
  },
  {
    id: "b-export-cdo",
    name: "Northern Mindanao Coco Exporters",
    role: "buyer",
    location: CITY.cdo,
    products: ["copra", "desiccated"],
    capacityTons: 180,
    disasterStatus: "unaffected",
    routeStatus: "limited",
    pricePhpPerTon: 42800,
    verified: true,
    rating: 4.6,
  },
  {
    id: "b-trader-tagum",
    name: "Tagum Valley Traders",
    role: "buyer",
    location: CITY.tagum,
    products: ["copra", "husk"],
    capacityTons: 60,
    disasterStatus: "at_risk",
    routeStatus: "open",
    pricePhpPerTon: 39800,
    verified: false,
    rating: 4.0,
  },
  {
    id: "b-broker-mati",
    name: "Mati Coastal Copra Buyers",
    role: "buyer",
    location: CITY.mati,
    products: ["copra"],
    capacityTons: 75,
    disasterStatus: "affected",
    routeStatus: "blocked",
    pricePhpPerTon: 45500,
    verified: false,
    rating: 3.8,
  },
  {
    id: "b-oil-koronadal",
    name: "Koronadal Coco Oil Refiners",
    role: "buyer",
    location: CITY.koronadal,
    products: ["copra", "coconut_oil"],
    capacityTons: 130,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 41000,
    verified: true,
    rating: 4.4,
  },

  // ---- Suppliers (of copra to processors) ----
  {
    id: "s-farm-kidapawan",
    name: "Kidapawan Farmers Assn.",
    role: "supplier",
    location: CITY.kidapawan,
    products: ["copra", "husk"],
    capacityTons: 110,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 39500,
    verified: true,
    rating: 4.6,
  },
  {
    id: "s-coop-bukidnon",
    name: "Bukidnon Coconut Cooperative",
    role: "supplier",
    location: CITY.malaybalay,
    products: ["copra", "coir"],
    capacityTons: 160,
    disasterStatus: "unaffected",
    routeStatus: "limited",
    pricePhpPerTon: 40100,
    verified: true,
    rating: 4.5,
  },
  {
    id: "s-estate-butuan",
    name: "Agusan Coco Estate",
    role: "supplier",
    location: CITY.butuan,
    products: ["copra", "coconut_oil"],
    capacityTons: 95,
    disasterStatus: "at_risk",
    routeStatus: "open",
    pricePhpPerTon: 41800,
    verified: true,
    rating: 4.2,
  },
  {
    id: "s-grower-cotabato",
    name: "Cotabato Smallholder Growers",
    role: "supplier",
    location: CITY.cotabato,
    products: ["copra"],
    capacityTons: 70,
    disasterStatus: "affected",
    routeStatus: "blocked",
    pricePhpPerTon: 43900,
    verified: false,
    rating: 3.9,
  },
  {
    id: "s-farm-zambo",
    name: "Zamboanga Peninsula Copra",
    role: "supplier",
    location: CITY.zambo,
    products: ["copra"],
    capacityTons: 140,
    disasterStatus: "unaffected",
    routeStatus: "limited",
    pricePhpPerTon: 38900,
    verified: true,
    rating: 4.3,
  },
  {
    id: "b-luzon-manila",
    name: "Luzon Premier Oils",
    role: "buyer",
    location: CITY.manila,
    products: ["coconut_oil"],
    capacityTons: 500,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 42500,
    verified: true,
    rating: 4.8,
  },
  {
    id: "b-visayas-cebu",
    name: "Visayas Copra Traders",
    role: "buyer",
    location: CITY.cebu,
    products: ["copra", "whole_nuts"],
    capacityTons: 150,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 41000,
    verified: true,
    rating: 4.5,
  },
  {
    id: "s-visayas-iloilo",
    name: "Panay Agri-Coop",
    role: "supplier",
    location: CITY.iloilo,
    products: ["copra"],
    capacityTons: 80,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 40500,
    verified: true,
    rating: 4.4,
  },
  {
    id: "s-luzon-baguio",
    name: "Cordillera Highland Farms",
    role: "supplier",
    location: CITY.baguio,
    products: ["whole_nuts"],
    capacityTons: 40,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 8700,
    verified: true,
    rating: 4.2,
  },
  {
    id: "b-luzon-batangas",
    name: "Batangas Coco Processing",
    role: "buyer",
    location: CITY.batangas,
    products: ["copra", "coconut_oil"],
    capacityTons: 300,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 41200,
    verified: true,
    rating: 4.7,
  },
  {
    id: "s-visayas-bacolod",
    name: "Negros Occidental Growers",
    role: "supplier",
    location: CITY.bacolod,
    products: ["copra"],
    capacityTons: 110,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 40000,
    verified: true,
    rating: 4.5,
  },
  {
    id: "s-visayas-tacloban",
    name: "Leyte Eastern Copra",
    role: "supplier",
    location: CITY.tacloban,
    products: ["copra", "whole_nuts"],
    capacityTons: 90,
    disasterStatus: "unaffected",
    routeStatus: "open",
    pricePhpPerTon: 39500,
    verified: false,
    rating: 4.1,
  }
];

/**
 * The signed-in SME for the demo: a Davao City copra trader whose main buyer
 * (Mati) and a backup supplier (Cotabato) are knocked out by a typhoon.
 */
export const DEMO_BUSINESS: BusinessProfile = {
  id: "sme-dahlia",
  name: "Dahlia Copra Trading",
  role: "trader",
  location: CITY.davao,
  products: ["copra"],
  monthlyVolumeTons: 65,
  currentPartners: [
    NETWORK.find((partner) => partner.id === "b-broker-mati")!,
    NETWORK.find((partner) => partner.id === "b-mill-digos")!,
    NETWORK.find((partner) => partner.id === "s-grower-cotabato")!,
  ],
};

/** Fair reference prices (PHP/ton) used to flag post-disaster price gouging. */
export const REFERENCE_PRICE: Record<string, number> = {
  copra: 41000,
  whole_nut: 8500,
  coconut_oil: 68000,
  desiccated: 52000,
  coir: 18000,
  husk: 9000,
  coco_water: 26000,
};

/**
 * Demo supplier profile: Kidapawan Farmers Assn. — used for the Supplier Portal.
 * Shows live inventory of copra and whole nuts.
 */
export const DEMO_SUPPLIER = {
  id: "s-farm-kidapawan",
  name: "Kidapawan Farmers Assn.",
  location: CITY.kidapawan,
  verified: true,
  rating: 4.6,
  activeBuyerCount: 3,
  disasterStatus: "unaffected" as const,
  stock: [
    {
      product: "copra" as const,
      label: "Copra",
      availableTons: 82,
      totalCapacityTons: 110,
      pricePhpPerTon: 39500,
      freshnessDays: 18,
      routeStatus: "open" as const,
    },
    {
      product: "whole_nut" as const,
      label: "Whole Coconut",
      availableTons: 34,
      totalCapacityTons: 60,
      pricePhpPerTon: 8200,
      freshnessDays: 7,
      routeStatus: "open" as const,
    },
    {
      product: "husk" as const,
      label: "Coconut Husk",
      availableTons: 15,
      totalCapacityTons: 40,
      pricePhpPerTon: 9000,
      freshnessDays: 30,
      routeStatus: "limited" as const,
    },
  ],
};
